version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "budgetbot-serverless"
region = "il-central-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
parameter_overrides = "BudgetbotSecretArn=\"arn:aws:secretsmanager:il-central-1:975050177457:secret:budgetbot/prod-pr82Vh\" BudgetbotKmsKeyArn=\"arn:aws:kms:il-central-1:975050177457:key/80836199-e239-471f-90ae-9a9b5cde3ec4\" LegacyKmsKeyArn=\"arn:aws:kms:il-central-1:975050177457:key/85ed0cae-1e8b-4666-8af7-04439c99c12c\" DynamoRecipientsTable=\"budgetbot-prod-recipients\" DynamoBalanceStateTable=\"budgetbot-prod-balance-state\" DynamoYnabConnectionsTable=\"budgetbot-prod-ynab-connections\" SpringProfile=\"prod\" DailySchedule=\"cron(0 7 * * ? *)\" DailyScheduleTimezone=\"Asia/Jerusalem\""
s3_prefix = "budgetbot-serverless"
image_repositories = []

[default.global.parameters]
region = "il-central-1"
